### ISSUE TITLE
error when run setup.py

### ISSUE THREAD

**Issue by dreamroboat** [stefan-ainetter/grasp_det_seg_cnn#12]
when I run setup.py, I met this error as follow:
(pytorch) robot@robot1503:/home/coding/Vscode/program/grasp_det_seg_cnn-main$ python setup.py install
/home/robot/anaconda3/envs/pytorch/lib/python3.7/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  SetuptoolsDeprecationWarning,
Traceback (most recent call last):
  File "setup.py", line 77, in <module>
    include_package_data=True,
  File "/home/robot/anaconda3/envs/pytorch/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/robot/anaconda3/envs/pytorch/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 109, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/robot/anaconda3/envs/pytorch/lib/python3.7/site-packages/setuptools/dist.py", line 481, in __init__
    for k, v in attrs.items()
  File "/home/robot/anaconda3/envs/pytorch/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
    self.finalize_options()
  File "/home/robot/anaconda3/envs/pytorch/lib/python3.7/site-packages/setuptools/dist.py", line 901, in finalize_options
    ep(self)
  File "/home/robot/anaconda3/envs/pytorch/lib/python3.7/site-packages/setuptools/dist.py", line 922, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/home/coding/Vscode/program/grasp_det_seg_cnn-main/.eggs/setuptools_scm-6.4.2-py3.7.egg/setuptools_scm/integration.py", line 75, in version_keyword
    _assign_version(dist, config)
  File "/home/coding/Vscode/program/grasp_det_seg_cnn-main/.eggs/setuptools_scm-6.4.2-py3.7.egg/setuptools_scm/integration.py", line 51, in _assign_version
    _version_missing(config)
  File "/home/coding/Vscode/program/grasp_det_seg_cnn-main/.eggs/setuptools_scm-6.4.2-py3.7.egg/setuptools_scm/__init__.py", line 107, in _version_missing
    f"setuptools-scm was unable to detect version for {config.absolute_root}.\n\n"
LookupError: setuptools-scm was unable to detect version for /home/coding/Vscode/program/grasp_det_seg_cnn-main.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

**Comment by niu17** [comment]
Hello,I made the same mistake.
Have you solved it?
Do you need to change the version of setuptools_scm?

**Comment by scq6688** [comment]
您好，请问train_det_seg_OCID.py您跑通了吗？我感觉数据集好像有点问题。出现这种错误。[图片]

**Comment by t-272** [comment]
have you solved it?
