### ISSUE TITLE
when i run train_det_seg_OCID.py ,have error . Is there a problem with the dataset?

### ISSUE THREAD

**Issue by scq6688** [stefan-ainetter/grasp_det_seg_cnn#15]
Traceback (most recent call last):
  File "train_det_seg_OCID.py", line 487, in <module>
    main(parser.parse_args())
  File "train_det_seg_OCID.py", line 458, in main
    global_step=global_step, loss_weights=config["optimizer"].getstruct("loss_weights"))
  File "train_det_seg_OCID.py", line 274, in train
    losses, _, conf = model(**batch, do_loss=True, do_prediction=False)
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/site-packages/GraspDetSeg_CNN-0.1.dev21+g980b761.d20220719-py3.6-linux-x86_64.egg/grasp_det_seg/models/det_seg.py", line 76, in forward
    self.rpn_head, x, bbx, iscrowd, valid_size, training=self.training, do_inference=True)
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/site-packages/GraspDetSeg_CNN-0.1.dev21+g980b761.d20220719-py3.6-linux-x86_64.egg/grasp_det_seg/algos/fpn.py", line 94, in training
    match = self.anchor_matcher(anchors, bbx, iscrowd, valid_size)
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/site-packages/GraspDetSeg_CNN-0.1.dev21+g980b761.d20220719-py3.6-linux-x86_64.egg/grasp_det_seg/algos/rpn.py", line 156, in __call__
    iou_max, iou_idx = iou.max(dim=1)
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity
Traceback (most recent call last):
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/scq/anaconda3/envs/yuyi/bin/python3', '-u', 'train_det_seg_OCID.py', '--local_rank=0', '--log_dir=LOGDIR', '/home/scq/grasp_det_seg_cnn/grasp_det_seg/config/defaults/det_seg_OCID.ini', '/home/scq/grasp_det_seg_cnn/DATA/OCID_grasp/data_split']' returned non-zero exit status 1.

**Comment by scq6688** [comment]
python3 -m torch.distributed.launch --nproc_per_node=1 train_det_seg_OCID.py --log_dir=LOGDIR /home/scq/grasp_det_seg_cnn/grasp_det_seg/config/defaults/det_seg_OCID.ini /home/scq/grasp_det_seg_cnn/DATA/OCID_grasp/data_split
23:00:37 Loading configuration from /home/scq/grasp_det_seg_cnn/grasp_det_seg/config/defaults/det_seg_OCID.ini
23:00:37 
[general]
val_interval = 25
log_interval = 10
cudnn_benchmark = no
num_classes = 18
num_stuff = 0
num_things = 18
num_semantic = 32

[body]
body = resnet50
weights = /home/scq/grasp_det_seg_cnn/weights_pretrained/resnet50
normalization_mode = syncbn
activation = leaky_relu
activation_slope = 0.01
gn_groups = 16
body_params = {}
num_frozen = 2
bn_frozen = yes
out_channels = {"mod1": 64, "mod2": 256, "mod3": 512, "mod4": 1024, "mod5": 2048}
out_strides = {"mod1": 4, "mod2": 4, "mod3": 8, "mod4": 16, "mod5": 32}

[fpn]
out_channels = 256
extra_scales = 0
interpolation = nearest
inputs = ["mod2", "mod3", "mod4", "mod5"]
out_strides = (4, 8, 16, 32)

[rpn]
hidden_channels = 256
stride = 1
anchor_ratios = (1., 0.1, 0.4, 0.7, 1.2)
anchor_scale = 2
nms_threshold = 0.7
num_pre_nms_train = 12000
num_post_nms_train = 2000
num_pre_nms_val = 6000
num_post_nms_val = 300
min_size = 16
num_samples = 256
pos_ratio = .5
pos_threshold = .7
neg_threshold = .3
void_threshold = 0.7
fpn_min_level = 0
fpn_levels = 3
sigma = 3.

[roi]
roi_size = (14, 14)
num_samples = 128
pos_ratio = .25
pos_threshold = .5
neg_threshold_hi = .5
neg_threshold_lo = 0.
void_threshold = 0.7
void_is_background = no
nms_threshold = 0.3
score_threshold = 0.05
max_predictions = 100
fpn_min_level = 0
fpn_levels = 4
fpn_canonical_scale = 224
fpn_canonical_level = 2
sigma = 1.
bbx_reg_weights = (10., 10., 5., 5.)

[sem]
fpn_min_level = 0
fpn_levels = 4
pooling_size = (64, 64)
ohem = .25

[optimizer]
lr = 0.03
weight_decay = 0.0001
weight_decay_norm = yes
momentum = 0.9
nesterov = yes
loss_weights = (1., 1., 1., 1.,.75)

[scheduler]
epochs = 50
type = poly
update_mode = batch
params = {"gamma": 0.9}
burn_in_steps = 500
burn_in_start = 0.333

[dataloader]
root_path = /home/scq/grasp_det_seg_cnn/DATA/OCID_grasp
shortest_size = 320
longest_max_size = 320
train_batch_size = 6
val_batch_size = 1
rgb_mean = (0.485, 0.456, 0.406)
rgb_std = (0.229, 0.224, 0.225)
random_flip = no
random_scale = None
rotate_and_scale = True
num_workers = 6
train_set = training_0
val_set = validation_0
test_set = validation_0


23:00:37 Creating dataloaders for dataset in /home/scq/grasp_det_seg_cnn/DATA/OCID_grasp/data_split
23:00:37 Creating backbone model resnet50
23:00:37 Starting epoch 1
23:00:42 [ 1/50] [ 10/235]	lr=0.000	loss=4.666 (4.908)	obj_loss=0.448 (0.557)	bbx_loss=0.119 (0.085)	roi_cls_loss=1.322 (1.577)	roi_bbx_loss=0.269 (0.244)	sem_loss=3.344 (3.262)	data_time=0.004 (0.046)	batch_time=0.534 (0.452)
23:00:47 [ 1/50] [ 20/235]	lr=0.000	loss=3.854 (4.500)	obj_loss=0.283 (0.457)	bbx_loss=0.056 (0.078)	roi_cls_loss=1.184 (1.384)	roi_bbx_loss=0.335 (0.255)	sem_loss=2.661 (3.101)	data_time=0.003 (0.024)	batch_time=0.433 (0.457)
23:00:51 [ 1/50] [ 30/235]	lr=0.000	loss=4.064 (4.312)	obj_loss=0.377 (0.422)	bbx_loss=0.088 (0.081)	roi_cls_loss=1.183 (1.310)	roi_bbx_loss=0.297 (0.252)	sem_loss=2.825 (2.996)	data_time=0.003 (0.017)	batch_time=0.430 (0.448)
23:00:56 [ 1/50] [ 40/235]	lr=0.000	loss=4.352 (4.141)	obj_loss=0.414 (0.398)	bbx_loss=0.079 (0.080)	roi_cls_loss=1.242 (1.263)	roi_bbx_loss=0.258 (0.253)	sem_loss=3.145 (2.863)	data_time=0.003 (0.013)	batch_time=0.449 (0.446)
23:01:00 [ 1/50] [ 50/235]	lr=0.000	loss=4.176 (4.123)	obj_loss=0.345 (0.395)	bbx_loss=0.089 (0.084)	roi_cls_loss=1.264 (1.255)	roi_bbx_loss=0.291 (0.260)	sem_loss=2.918 (2.840)	data_time=0.003 (0.011)	batch_time=0.439 (0.447)
23:01:05 [ 1/50] [ 60/235]	lr=0.000	loss=3.849 (4.057)	obj_loss=0.362 (0.379)	bbx_loss=0.086 (0.082)	roi_cls_loss=1.173 (1.244)	roi_bbx_loss=0.291 (0.270)	sem_loss=2.583 (2.775)	data_time=0.003 (0.010)	batch_time=0.456 (0.446)
NO valid boxes after augmentation, switch to gt values
23:01:10 [ 1/50] [ 70/235]	lr=0.000	loss=3.915 (4.036)	obj_loss=0.304 (0.373)	bbx_loss=0.068 (0.082)	roi_cls_loss=1.223 (1.241)	roi_bbx_loss=0.298 (0.276)	sem_loss=2.696 (2.753)	data_time=0.003 (0.009)	batch_time=0.514 (0.454)
NO valid boxes after augmentation, switch to gt values
23:01:15 [ 1/50] [ 80/235]	lr=0.000	loss=2.950 (3.962)	obj_loss=0.282 (0.365)	bbx_loss=0.064 (0.081)	roi_cls_loss=1.084 (1.234)	roi_bbx_loss=0.238 (0.278)	sem_loss=1.709 (2.672)	data_time=0.003 (0.008)	batch_time=0.513 (0.462)
23:01:20 [ 1/50] [ 90/235]	lr=0.000	loss=4.107 (3.897)	obj_loss=0.328 (0.359)	bbx_loss=0.094 (0.081)	roi_cls_loss=1.268 (1.220)	roi_bbx_loss=0.306 (0.276)	sem_loss=2.815 (2.614)	data_time=0.003 (0.007)	batch_time=0.487 (0.467)
23:01:25 [ 1/50] [100/235]	lr=0.000	loss=3.372 (3.850)	obj_loss=0.341 (0.356)	bbx_loss=0.077 (0.082)	roi_cls_loss=1.212 (1.219)	roi_bbx_loss=0.266 (0.279)	sem_loss=1.968 (2.552)	data_time=0.003 (0.007)	batch_time=0.465 (0.469)
NO valid boxes after augmentation, switch to gt values
23:01:29 [ 1/50] [110/235]	lr=0.000	loss=3.678 (3.767)	obj_loss=0.302 (0.347)	bbx_loss=0.076 (0.080)	roi_cls_loss=1.247 (1.209)	roi_bbx_loss=0.273 (0.279)	sem_loss=2.374 (2.469)	data_time=0.003 (0.006)	batch_time=0.471 (0.468)
Traceback (most recent call last):
  File "train_det_seg_OCID.py", line 487, in <module>
    main(parser.parse_args())
  File "train_det_seg_OCID.py", line 458, in main
    global_step=global_step, loss_weights=config["optimizer"].getstruct("loss_weights"))
  File "train_det_seg_OCID.py", line 274, in train
    losses, _, conf = model(**batch, do_loss=True, do_prediction=False)
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/site-packages/GraspDetSeg_CNN-0.1.dev21+g980b761.d20220719-py3.6-linux-x86_64.egg/grasp_det_seg/models/det_seg.py", line 76, in forward
    self.rpn_head, x, bbx, iscrowd, valid_size, training=self.training, do_inference=True)
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/site-packages/GraspDetSeg_CNN-0.1.dev21+g980b761.d20220719-py3.6-linux-x86_64.egg/grasp_det_seg/algos/fpn.py", line 94, in training
    match = self.anchor_matcher(anchors, bbx, iscrowd, valid_size)
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/site-packages/GraspDetSeg_CNN-0.1.dev21+g980b761.d20220719-py3.6-linux-x86_64.egg/grasp_det_seg/algos/rpn.py", line 156, in __call__
    iou_max, iou_idx = iou.max(dim=1)
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity
Traceback (most recent call last):
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/scq/anaconda3/envs/yuyi/lib/python3.6/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/scq/anaconda3/envs/yuyi/bin/python3', '-u', 'train_det_seg_OCID.py', '--local_rank=0', '--log_dir=LOGDIR', '/home/scq/grasp_det_seg_cnn/grasp_det_seg/config/defaults/det_seg_OCID.ini', '/home/scq/grasp_det_seg_cnn/DATA/OCID_grasp/data_split']' returned non-zero exit status 1.
