### ISSUE TITLE
Setup.py error (ValueError: bad marshal data )

### ISSUE THREAD

**Issue by enesdoruk** [stefan-ainetter/grasp_det_seg_cnn#22]
Hi, i installed pytorch from source and install requirements.txt, I use cuda 10.2 and  Cudnn 7.5, when i command setup.py, i get error. I spend 2 days for this problem. I downloaded seamseg repo and setup.py works. but in this repo i get problem. please help me. 

==============================================================

zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 77, in <module>
    include_package_data=True,
  File "/home/enesdrk/.local/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/enesdrk/.local/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/enesdrk/.local/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/enesdrk/.local/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/enesdrk/.local/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/enesdrk/.local/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/enesdrk/.local/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/enesdrk/.local/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/enesdrk/.local/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/enesdrk/.local/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/enesdrk/.local/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/enesdrk/.local/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 213, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/home/enesdrk/.local/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 266, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/home/enesdrk/.local/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 340, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/home/enesdrk/.local/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 377, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)

**Comment by enesdoruk** [comment]
and i installed pytorch from source and support python why i insalled pytorch via pip again, i dont understand

**Comment by enesdoruk** [comment]
it works. 

Should add  zip_safe=False in setuptools_setup in setup.py

setuptools.setup(
    # Meta-data
    name="GraspDetSeg_CNN",
    zip_safe=False,
    author="Stefan Ainetter",
    author_email="stefan.ainetter@icg.tugraz.at",
    description="Grasp Detection and Segmentation for Pytorch, code based on Seamless Scene Segmentation (https://github.com/mapillary/seamseg).",
    long_description_content_type="text/markdown",
    url="",
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.4",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
    ],
