### ISSUE TITLE
issue with setup.py install 

### ISSUE THREAD

**Issue by hensleyabcd** [stefan-ainetter/grasp_det_seg_cnn#30]
Hello,

I am trying to install the repo into my laptop. But I am getting the following error:

/home/src/env/lib/python3.8/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
running install
/home/src/env/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/src/env/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing GraspDetSeg_CNN.egg-info/PKG-INFO
writing dependency_links to GraspDetSeg_CNN.egg-info/dependency_links.txt
writing top-level names to GraspDetSeg_CNN.egg-info/top_level.txt
adding license file 'LICENSE'
writing manifest file 'GraspDetSeg_CNN.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying grasp_det_seg/_version.py -> build/lib.linux-x86_64-cpython-38/grasp_det_seg
/home/src/env/lib/python3.8/site-packages/setuptools/command/build_py.py:201: _Warning: Package 'grasp_det_seg.__pycache__' is absent from the `packages` configuration.
!!

        ********************************************************************************
        ############################
        # Package would be ignored #
        ############################
        Python recognizes 'grasp_det_seg.__pycache__' as an importable package[^1],
        but it is absent from setuptools' `packages` configuration.

        This leads to an ambiguous overall configuration. If you want to distribute this
        package, please make sure that 'grasp_det_seg.__pycache__' is explicitly added
        to the `packages` configuration field.

        Alternatively, you can also rely on setuptools' discovery methods
        (for example by using `find_namespace_packages(...)`/`find_namespace:`
        instead of `find_packages(...)`/`find:`).

        You can read more about "package discovery" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

        If you don't want 'grasp_det_seg.__pycache__' to be distributed and are
        already explicitly excluding 'grasp_det_seg.__pycache__' via
        `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
        you can try to use `exclude_package_data`, or `include-package-data=False` in
        combination with a more fine grained `package-data` configuration.

        You can read more about "package data files" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

        [^1]: For Python, any directory (with suitable naming) can be imported,
              even if it does not contain any `.py` files.
              On the other hand, currently there is no concept of package data
              directory, all directories are treated like packages.
        ********************************************************************************

!!
  check.warn(importable)
/home/src/env/lib/python3.8/site-packages/setuptools/command/build_py.py:201: _Warning: Package 'grasp_det_seg.algos.__pycache__' is absent from the `packages` configuration.
!!

        ********************************************************************************
        ############################
        # Package would be ignored #
        ############################
        Python recognizes 'grasp_det_seg.algos.__pycache__' as an importable package[^1],
        but it is absent from setuptools' `packages` configuration.

        This leads to an ambiguous overall configuration. If you want to distribute this
        package, please make sure that 'grasp_det_seg.algos.__pycache__' is explicitly added
        to the `packages` configuration field.

        Alternatively, you can also rely on setuptools' discovery methods
        (for example by using `find_namespace_packages(...)`/`find_namespace:`
        instead of `find_packages(...)`/`find:`).

        You can read more about "package discovery" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

        If you don't want 'grasp_det_seg.algos.__pycache__' to be distributed and are
        already explicitly excluding 'grasp_det_seg.algos.__pycache__' via
        `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
        you can try to use `exclude_package_data`, or `include-package-data=False` in
        combination with a more fine grained `package-data` configuration.

        You can read more about "package data files" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

        [^1]: For Python, any directory (with suitable naming) can be imported,
              even if it does not contain any `.py` files.
              On the other hand, currently there is no concept of package data
              directory, all directories are treated like packages.
        ********************************************************************************

!!
  check.warn(importable)
/home/src/env/lib/python3.8/site-packages/setuptools/command/build_py.py:201: _Warning: Package 'grasp_det_seg.config.defaults' is absent from the `packages` configuration.
!!

        ********************************************************************************
        ############################
        # Package would be ignored #
        ############################
        Python recognizes 'grasp_det_seg.config.defaults' as an importable package[^1],
        but it is absent from setuptools' `packages` configuration.

        This leads to an ambiguous overall configuration. If you want to distribute this
        package, please make sure that 'grasp_det_seg.config.defaults' is explicitly added
        to the `packages` configuration field.

        Alternatively, you can also rely on setuptools' discovery methods
        (for example by using `find_namespace_packages(...)`/`find_namespace:`
        instead of `find_packages(...)`/`find:`).

        You can read more about "package discovery" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

        If you don't want 'grasp_det_seg.config.defaults' to be distributed and are
        already explicitly excluding 'grasp_det_seg.config.defaults' via
        `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
        you can try to use `exclude_package_data`, or `include-package-data=False` in
        combination with a more fine grained `package-data` configuration.

        You can read more about "package data files" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

        [^1]: For Python, any directory (with suitable naming) can be imported,
              even if it does not contain any `.py` files.
              On the other hand, currently there is no concept of package data
              directory, all directories are treated like packages.
        ********************************************************************************

!!
  check.warn(importable)
/home/src/env/lib/python3.8/site-packages/setuptools/command/build_py.py:201: _Warning: Package 'grasp_det_seg.models.__pycache__' is absent from the `packages` configuration.
!!

        ********************************************************************************
        ############################
        # Package would be ignored #
        ############################
        Python recognizes 'grasp_det_seg.models.__pycache__' as an importable package[^1],
        but it is absent from setuptools' `packages` configuration.

        This leads to an ambiguous overall configuration. If you want to distribute this
        package, please make sure that 'grasp_det_seg.models.__pycache__' is explicitly added
        to the `packages` configuration field.

        Alternatively, you can also rely on setuptools' discovery methods
        (for example by using `find_namespace_packages(...)`/`find_namespace:`
        instead of `find_packages(...)`/`find:`).

        You can read more about "package discovery" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

        If you don't want 'grasp_det_seg.models.__pycache__' to be distributed and are
        already explicitly excluding 'grasp_det_seg.models.__pycache__' via
        `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
        you can try to use `exclude_package_data`, or `include-package-data=False` in
        combination with a more fine grained `package-data` configuration.

        You can read more about "package data files" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

        [^1]: For Python, any directory (with suitable naming) can be imported,
              even if it does not contain any `.py` files.
              On the other hand, currently there is no concept of package data
              directory, all directories are treated like packages.
        ********************************************************************************

!!
  check.warn(importable)
/home/src/env/lib/python3.8/site-packages/setuptools/command/build_py.py:201: _Warning: Package 'grasp_det_seg.modules.__pycache__' is absent from the `packages` configuration.
!!

        ********************************************************************************
        ############################
        # Package would be ignored #
        ############################
        Python recognizes 'grasp_det_seg.modules.__pycache__' as an importable package[^1],
        but it is absent from setuptools' `packages` configuration.

        This leads to an ambiguous overall configuration. If you want to distribute this
        package, please make sure that 'grasp_det_seg.modules.__pycache__' is explicitly added
        to the `packages` configuration field.

        Alternatively, you can also rely on setuptools' discovery methods
        (for example by using `find_namespace_packages(...)`/`find_namespace:`
        instead of `find_packages(...)`/`find:`).

        You can read more about "package discovery" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

        If you don't want 'grasp_det_seg.modules.__pycache__' to be distributed and are
        already explicitly excluding 'grasp_det_seg.modules.__pycache__' via
        `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
        you can try to use `exclude_package_data`, or `include-package-data=False` in
        combination with a more fine grained `package-data` configuration.

        You can read more about "package data files" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

        [^1]: For Python, any directory (with suitable naming) can be imported,
              even if it does not contain any `.py` files.
              On the other hand, currently there is no concept of package data
              directory, all directories are treated like packages.
        ********************************************************************************

!!
  check.warn(importable)
/home/src/env/lib/python3.8/site-packages/setuptools/command/build_py.py:201: _Warning: Package 'grasp_det_seg.utils.__pycache__' is absent from the `packages` configuration.
!!

        ********************************************************************************
        ############################
        # Package would be ignored #
        ############################
        Python recognizes 'grasp_det_seg.utils.__pycache__' as an importable package[^1],
        but it is absent from setuptools' `packages` configuration.

        This leads to an ambiguous overall configuration. If you want to distribute this
        package, please make sure that 'grasp_det_seg.utils.__pycache__' is explicitly added
        to the `packages` configuration field.

        Alternatively, you can also rely on setuptools' discovery methods
        (for example by using `find_namespace_packages(...)`/`find_namespace:`
        instead of `find_packages(...)`/`find:`).

        You can read more about "package discovery" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

        If you don't want 'grasp_det_seg.utils.__pycache__' to be distributed and are
        already explicitly excluding 'grasp_det_seg.utils.__pycache__' via
        `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
        you can try to use `exclude_package_data`, or `include-package-data=False` in
        combination with a more fine grained `package-data` configuration.

        You can read more about "package data files" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

        [^1]: For Python, any directory (with suitable naming) can be imported,
              even if it does not contain any `.py` files.
              On the other hand, currently there is no concept of package data
              directory, all directories are treated like packages.
        ********************************************************************************

!!
  check.warn(importable)
/home/src/env/lib/python3.8/site-packages/setuptools/command/build_py.py:201: _Warning: Package 'grasp_det_seg.utils.bbx.__pycache__' is absent from the `packages` configuration.
!!

        ********************************************************************************
        ############################
        # Package would be ignored #
        ############################
        Python recognizes 'grasp_det_seg.utils.bbx.__pycache__' as an importable package[^1],
        but it is absent from setuptools' `packages` configuration.

        This leads to an ambiguous overall configuration. If you want to distribute this
        package, please make sure that 'grasp_det_seg.utils.bbx.__pycache__' is explicitly added
        to the `packages` configuration field.

        Alternatively, you can also rely on setuptools' discovery methods
        (for example by using `find_namespace_packages(...)`/`find_namespace:`
        instead of `find_packages(...)`/`find:`).

        You can read more about "package discovery" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

        If you don't want 'grasp_det_seg.utils.bbx.__pycache__' to be distributed and are
        already explicitly excluding 'grasp_det_seg.utils.bbx.__pycache__' via
        `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
        you can try to use `exclude_package_data`, or `include-package-data=False` in
        combination with a more fine grained `package-data` configuration.

        You can read more about "package data files" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

        [^1]: For Python, any directory (with suitable naming) can be imported,
              even if it does not contain any `.py` files.
              On the other hand, currently there is no concept of package data
              directory, all directories are treated like packages.
        ********************************************************************************

!!
  check.warn(importable)
/home/src/env/lib/python3.8/site-packages/setuptools/command/build_py.py:201: _Warning: Package 'grasp_det_seg.utils.parallel.__pycache__' is absent from the `packages` configuration.
!!

        ********************************************************************************
        ############################
        # Package would be ignored #
        ############################
        Python recognizes 'grasp_det_seg.utils.parallel.__pycache__' as an importable package[^1],
        but it is absent from setuptools' `packages` configuration.

        This leads to an ambiguous overall configuration. If you want to distribute this
        package, please make sure that 'grasp_det_seg.utils.parallel.__pycache__' is explicitly added
        to the `packages` configuration field.

        Alternatively, you can also rely on setuptools' discovery methods
        (for example by using `find_namespace_packages(...)`/`find_namespace:`
        instead of `find_packages(...)`/`find:`).

        You can read more about "package discovery" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

        If you don't want 'grasp_det_seg.utils.parallel.__pycache__' to be distributed and are
        already explicitly excluding 'grasp_det_seg.utils.parallel.__pycache__' via
        `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
        you can try to use `exclude_package_data`, or `include-package-data=False` in
        combination with a more fine grained `package-data` configuration.

        You can read more about "package data files" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

        [^1]: For Python, any directory (with suitable naming) can be imported,
              even if it does not contain any `.py` files.
              On the other hand, currently there is no concept of package data
              directory, all directories are treated like packages.
        ********************************************************************************

!!
  check.warn(importable)
running build_ext
building 'grasp_det_seg.utils.nms._backend' extension
/home/src/env/lib/python3.8/site-packages/torch/cuda/__init__.py:106: UserWarning: 
NVIDIA GeForce RTX 3080 Ti with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3080 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Emitting ninja build file /home/src/grasp_det_seg_cnn/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] c++ -MMD -MF /home/src/grasp_det_seg_cnn/build/temp.linux-x86_64-cpython-38/src/nms/nms_cpu.o.d -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Iinclude/ -I/home/src/env/lib/python3.8/site-packages/torch/include -I/home/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/src/env/lib/python3.8/site-packages/torch/include/TH -I/home/src/env/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/src/env/include -I/usr/include/python3.8 -c -c /home/src/grasp_det_seg_cnn/src/nms/nms_cpu.cpp -o /home/src/grasp_det_seg_cnn/build/temp.linux-x86_64-cpython-38/src/nms/nms_cpu.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/src/grasp_det_seg_cnn/build/temp.linux-x86_64-cpython-38/src/nms/nms_cpu.o 
c++ -MMD -MF /home/src/grasp_det_seg_cnn/build/temp.linux-x86_64-cpython-38/src/nms/nms_cpu.o.d -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Iinclude/ -I/home/src/env/lib/python3.8/site-packages/torch/include -I/home/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/src/env/lib/python3.8/site-packages/torch/include/TH -I/home/src/env/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/src/env/include -I/usr/include/python3.8 -c -c /home/src/grasp_det_seg_cnn/src/nms/nms_cpu.cpp -o /home/src/grasp_det_seg_cnn/build/temp.linux-x86_64-cpython-38/src/nms/nms_cpu.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
/home/src/grasp_det_seg_cnn/src/nms/nms_cpu.cpp:7:10: fatal error: nms.h: No such file or directory
    7 | #include "nms.h"
      |          ^~~~~~~
compilation terminated.
[2/3] c++ -MMD -MF /home/src/grasp_det_seg_cnn/build/temp.linux-x86_64-cpython-38/src/nms/nms.o.d -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Iinclude/ -I/home/src/env/lib/python3.8/site-packages/torch/include -I/home/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/src/env/lib/python3.8/site-packages/torch/include/TH -I/home/src/env/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/src/env/include -I/usr/include/python3.8 -c -c /home/src/grasp_det_seg_cnn/src/nms/nms.cpp -o /home/src/grasp_det_seg_cnn/build/temp.linux-x86_64-cpython-38/src/nms/nms.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/src/grasp_det_seg_cnn/build/temp.linux-x86_64-cpython-38/src/nms/nms.o 
c++ -MMD -MF /home/src/grasp_det_seg_cnn/build/temp.linux-x86_64-cpython-38/src/nms/nms.o.d -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Iinclude/ -I/home/src/env/lib/python3.8/site-packages/torch/include -I/home/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/src/env/lib/python3.8/site-packages/torch/include/TH -I/home/src/env/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/src/env/include -I/usr/include/python3.8 -c -c /home/src/grasp_det_seg_cnn/src/nms/nms.cpp -o /home/src/grasp_det_seg_cnn/build/temp.linux-x86_64-cpython-38/src/nms/nms.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
In file included from /home/src/env/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:140,
                 from /home/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                 from /home/src/env/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/src/grasp_det_seg_cnn/src/nms/nms.cpp:1:
/home/src/env/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:87: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
   87 | #pragma omp parallel for if ((end - begin) >= grain_size)
      | 
/home/src/grasp_det_seg_cnn/src/nms/nms.cpp:3:10: fatal error: nms.h: No such file or directory
    3 | #include "nms.h"
      |          ^~~~~~~
compilation terminated.
[3/3] /usr/local/cuda-11.3/bin/nvcc  -Iinclude/ -I/home/src/env/lib/python3.8/site-packages/torch/include -I/home/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/src/env/lib/python3.8/site-packages/torch/include/TH -I/home/src/env/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/homesrc/env/include -I/usr/include/python3.8 -c -c /home/src/grasp_det_seg_cnn/src/nms/nms_cuda.cu -o /home/src/grasp_det_seg_cnn/build/temp.linux-x86_64-cpython-38/src/nms/nms_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' --expt-extended-lambda -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++14
FAILED: /home/src/grasp_det_seg_cnn/build/temp.linux-x86_64-cpython-38/src/nms/nms_cuda.o 
/usr/local/cuda-11.3/bin/nvcc  -Iinclude/ -I/home/src/env/lib/python3.8/site-packages/torch/include -I/home/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/src/env/lib/python3.8/site-packages/torch/include/TH -I/home/src/env/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/src/env/include -I/usr/include/python3.8 -c -c /home/src/grasp_det_seg_cnn/src/nms/nms_cuda.cu -o /home/src/grasp_det_seg_cnn/build/temp.linux-x86_64-cpython-38/src/nms/nms_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' --expt-extended-lambda -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++14
/home/src/grasp_det_seg_cnn/src/nms/nms_cuda.cu:4:10: fatal error: nms.h: No such file or directory
    4 | #include "nms.h"
      |          ^~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/src/env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1666, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    setuptools.setup(
  File "/home/src/env/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/homesrc/env/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/src/env/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/src/env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/src/env/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/src/env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/src/env/lib/python3.8/site-packages/setuptools/command/install.py", line 80, in run
    self.do_egg_install()
  File "/home/src/env/lib/python3.8/site-packages/setuptools/command/install.py", line 129, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/src/env/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/src/env/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/src/env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/src/env/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/src/env/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/src/env/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/src/env/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/src/env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/src/env/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/src/env/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/home/src/env/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/src/env/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/src/env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/src/env/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/src/env/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/src/env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "/home/src/env/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/src/env/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/src/env/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/src/env/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/src/env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 530, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/src/env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/src/env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

Can someone help me resolve this ?

**Comment by gaoxiang12** [comment]
just add a line below line 77 of setup.py:

include_dirs=['./include'],

and then rebuild the project.

**Comment by Boggart386** [comment]
> just add a line below line 77 of setup.py:
> 
> include_dirs=['./include'],
> 
> and then rebuild the project.

Still not working sir. Really need help. The same problem as above.

**Comment by Boggart386** [comment]
Already solved using 'pip install -e .' instead of 'setup.py install'
